### ISSUE TITLE
Crash in debug world

### ISSUE THREAD

**Issue by Lolothepro** [JDKDigital/productivetrees#11]
Crash report: 
[crash-2024-07-18_19.29.37-server.txt](https://github.com/user-attachments/files/16288240/crash-2024-07-18_19.29.37-server.txt)

Log file:
[latest.log](https://github.com/user-attachments/files/16288243/latest.log)

NeoForge: 21.0.106-beta
Minecraft: 1.21
https://mclo.gs/rBpP629

```
java.lang.IllegalStateException: Cannot encode empty ItemStack
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.item.ItemStack.save(ItemStack.java:400) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/productivetrees@1.21.0-0.3.2/cy.jdkdigital.productivetrees.common.block.entity.PollinatedLeavesBlockEntity.savePacketNBT(PollinatedLeavesBlockEntity.java:103) ~[productivetrees-1.21.0-0.3.2.jar%23171!/:?] {re:classloading}
	at TRANSFORMER/productivetrees@1.21.0-0.3.2/cy.jdkdigital.productivetrees.common.block.entity.PollinatedLeavesBlockEntity.saveAdditional(PollinatedLeavesBlockEntity.java:61) ~[productivetrees-1.21.0-0.3.2.jar%23171!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.block.entity.BlockEntity.saveWithoutMetadata(BlockEntity.java:102) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.block.entity.BlockEntity.saveWithId(BlockEntity.java:95) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading}
	at TRANSFORMER/productivetrees@1.21.0-0.3.2/cy.jdkdigital.productivetrees.common.block.entity.PollinatedLeavesBlockEntity.getUpdateTag(PollinatedLeavesBlockEntity.java:66) ~[productivetrees-1.21.0-0.3.2.jar%23171!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.create(ClientboundLevelChunkPacketData.java:162) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:47) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:28) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.network.PlayerChunkSender.sendChunk(PlayerChunkSender.java:78) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.network.PlayerChunkSender.sendNextChunks(PlayerChunkSender.java:65) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1067) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21-20240613.152323-srg.jar%23169!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] {}

```

**Comment by JaisDK** [comment]
Can you walk me through how you created the pollinated leaf that is crashing?

**Comment by Lolothepro** [comment]
> Can you walk me through how you created the pollinated leaf that is crashing?

Debug world...?

**Comment by JaisDK** [comment]
no the steps for pollinating the tree, how you got the pollen which leaves you used and also if you got the pollen on an older version of the mod

**Comment by Lolothepro** [comment]
> no the steps for pollinating the tree, how you got the pollen which leaves you used and also if you got the pollen on an older version of the mod

No, I just loaded Minecraft's default debug world.
https://minecraft.wiki/w/Debug_mode

**Comment by JaisDK** [comment]
what on earth is that? it just places one of every block?


yea that is sure to crash as some modded blocks expect data to be set as well...

**Comment by Lolothepro** [comment]
> what on earth is that? it just places one of every block?
> 
> yea that is sure to crash as some modded blocks expect data to be set as well...

The mod shouldn't crash...?
It's just a debug world that displays every block states, every block, and texture... this debug world exists since Minecraft 1.8

**Comment by JaisDK** [comment]
having been around since 1.8 doesn't mean anyone knows about it and my point was that you shouldn't expect all mods blocks to be placeable without being placed in the right context

I will add crash guard at that spot now that I know about it

**Comment by JaisDK** [comment]
new version is up

I'm gonna go test all my other mods in debug world too :D
